"""remove permalink column from table user

Revision ID: 90cd3fd44a5a
Revises: b41d9a599b8f
Create Date: 2018-07-19 10:17:19.383632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90cd3fd44a5a'
down_revision = 'b41d9a599b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('permalink', table_name='user')
    op.drop_column('user', 'permalink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permalink', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False))
    op.create_index('permalink', 'user', ['permalink'], unique=True)
    # ### end Alembic commands ###
