"""Post: add status, change path to coding_path

Revision ID: ae3fb58327ad
Revises: c43282c43e56
Create Date: 2018-07-12 12:40:51.537578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae3fb58327ad'
down_revision = 'c43282c43e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('coding_path', sa.String(length=256), nullable=False))
    op.add_column('post', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('post', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=256), nullable=False))
    op.drop_column('post', 'status')
    op.drop_column('post', 'coding_path')
    # ### end Alembic commands ###
