"""change Post.coding_path to unique=True 

Revision ID: b41d9a599b8f
Revises: ae3fb58327ad
Create Date: 2018-07-12 12:47:05.041494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41d9a599b8f'
down_revision = 'ae3fb58327ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['coding_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
