"""add path to Post

Revision ID: c43282c43e56
Revises: 3b8a99ed18ef
Create Date: 2018-07-12 12:33:40.877181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43282c43e56'
down_revision = '3b8a99ed18ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('path', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'path')
    # ### end Alembic commands ###
